// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrB5toNvBq7wGA40Job1DmjaMgaUwnrIo',
    appId: '1:635907871961:web:997b7bf9fa30fd1ceb1ac8',
    messagingSenderId: '635907871961',
    projectId: 'mynotes-project-agbe',
    authDomain: 'mynotes-project-agbe.firebaseapp.com',
    storageBucket: 'mynotes-project-agbe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmXaq4fe-gPa5Ouv39IywwrbCIoeDcYCY',
    appId: '1:635907871961:android:71bdb14ef8c900aaeb1ac8',
    messagingSenderId: '635907871961',
    projectId: 'mynotes-project-agbe',
    storageBucket: 'mynotes-project-agbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR67yH-C9CmmdybowVIaQhVQ9l9aqFC6M',
    appId: '1:635907871961:ios:de34538bc59692f9eb1ac8',
    messagingSenderId: '635907871961',
    projectId: 'mynotes-project-agbe',
    storageBucket: 'mynotes-project-agbe.firebasestorage.app',
    iosBundleId: 'com.crameurcode.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR67yH-C9CmmdybowVIaQhVQ9l9aqFC6M',
    appId: '1:635907871961:ios:de34538bc59692f9eb1ac8',
    messagingSenderId: '635907871961',
    projectId: 'mynotes-project-agbe',
    storageBucket: 'mynotes-project-agbe.firebasestorage.app',
    iosBundleId: 'com.crameurcode.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrB5toNvBq7wGA40Job1DmjaMgaUwnrIo',
    appId: '1:635907871961:web:c24ac53c15503e28eb1ac8',
    messagingSenderId: '635907871961',
    projectId: 'mynotes-project-agbe',
    authDomain: 'mynotes-project-agbe.firebaseapp.com',
    storageBucket: 'mynotes-project-agbe.firebasestorage.app',
  );
}
